import type { Metadata } from 'next'
import '../globals.css'

export const metadata: Metadata = {
  title: 'Our Menu | Campione',
  description: 'Generated by create next app'
}

export default function MenuLayout ({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return <div>{children}</div>
}
